### ISSUE TITLE
PresenterClass::__construct() does not call parent constructor from Nette\Application\UI\Presenter

### ISSUE THREAD

**Issue by bazo** [phpstan/phpstan-nette#31]
I get an error for all presenters that they don't call parent constructor. why is this an error?

**Comment by ondrejmirtes** [comment]
Because you should call the parent constructor. It's a matter of encapsulation - the parent object is only consistent when its constructor is called.  It's weird to think when creating objects that someone can work around my constructor being called, leaving the object in potentially inconsistent state.
