### ISSUE TITLE
Nette forms callbacks

### ISSUE THREAD

**Issue by Sitole** [phpstan/phpstan-nette#42]
Hello,
currently I have encountered problems in testing applications because PHPStan started throwing exceptions for Nette Forms Form. He doesn't like callbacks.

`Array (array<callable(Nette\Forms\Form, mixed): void>) does not accept  
         Closure(Nette\Application\UI\Form, Nette\Utils\ArrayHash): void.`

for

```php
$form->onSuccess[] = function (Nette\Application\UI\Form $form, ArrayHash $values): void {
	...
}
```

`Array (array<callable(Nette\Forms\Form, mixed): void>) does not accept  
         array($this(App\Modules\Section\Presenters\Forum\ForumPresenter),       
         'onSuccess').`

for

```php
$form->onSuccess[] = [$this, 'onSuccess'];
```

Is there a solution via phpstan-nette extension to fix it?

**Comment by ondrejmirtes** [comment]
Hi, the problem is that the signature breaks LSP. When you have `array<callable(Nette\Forms\Form, mixed)`, it's unsafe to expect `Nette\Forms\Form` child class in the callback.

You should change it to this code:

```php
$form->onSuccess[] = function (\Nette\Forms\Form $form, ArrayHash $values): void {
	...
}
```

I get that Nette will probably work even with your code but that might change in the future without being able to detect that from the typesystem PoV.  So there's no way to fix it in the extension. You should probably put it in `ignoreErrors`.
